ALTER TABLE skills ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';

ALTER TABLE skill_versions ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';

ALTER TABLE executions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE approvals ADD COLUMN IF NOT EXISTS approved_by TEXT NULL;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS resolution_note TEXT NULL;
